server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_sample?useSSL=false&amp
    username: demo_sample
    password: password
    continueOnError: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      database: mysql
  profiles: dev

external-api:
  endpoint : https://randomuser.me/api/